// app/(dashboard)/colaboradores/novo/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Check, User, Briefcase, Mail, Phone, CreditCard, Building2 } from 'lucide-react'
import { z } from 'zod'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Alert } from '@/components/ui/alert'
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select'
import { createClient } from '@/lib/supabase/client'

const schema = z.object({
    full_name: z.string().min(3, 'Nome deve ter pelo menos 3 caracteres'),
    email: z.string().email('Email inválido'),
    department: z.string().min(1, 'Selecione um departamento'),
    role: z.string().min(1, 'Cargo é obrigatório'),
    cpf: z.string().optional(),
    phone: z.string().optional(),
})

const departmentsList = [
    'Administrativo',
    'Comercial',
    'Financeiro',
    'Marketing',
    'Operacional',
    'RH',
    'TI',
]

export default function NovoColaboradorPage() {
    const router = useRouter()
    const supabase = createClient()
    const [loading, setLoading] = useState(false)
    const [feedback, setFeedback] = useState<{ message: string; type: 'success' | 'error' } | null>(null)

    const [formData, setFormData] = useState({
        full_name: '',
        email: '',
        cpf: '',
        phone: '',
        department: '',
        role: '',
    })

    const handleChange = (field: string, value: string) => {
        setFormData((prev) => ({ ...prev, [field]: value }))
    }

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        setLoading(true)
        setFeedback(null)

        try {
            const validated = schema.parse(formData)

            const { error } = await supabase.from('collaborators').insert({
                full_name: validated.full_name,
                email: validated.email,
                status: 'ativo',
                department: validated.department,
            })

            if (error) throw error

            setFeedback({ message: 'Colaborador cadastrado com sucesso!', type: 'success' })
            setTimeout(() => router.push('/colaboradores'), 800)
        } catch (e: any) {
            console.error(e)
            if (e instanceof z.ZodError) {
                setFeedback({ message: e.errors[0].message, type: 'error' })
            } else {
                setFeedback({ message: 'Erro: ' + (e.message || e), type: 'error' })
            }
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="max-w-5xl mx-auto py-10 px-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-10">
                <div className="flex items-center gap-4">
                    <Link href="/colaboradores">
                        <Button
                            variant="outline"
                            size="icon"
                            className="rounded-full shadow-sm border border-gray-200 text-gray-700 hover:bg-gray-50"
                        >
                            <ArrowLeft className="w-5 h-5" />
                        </Button>
                    </Link>
                    <div>
                        <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight">
                            Novo Colaborador
                        </h1>
                        <p className="text-lg text-gray-500 mt-1">
                            Preencha a ficha cadastral para admissão.
                        </p>
                    </div>
                </div>
            </div>

            {feedback && (
                <div className="mb-6">
                    <Alert variant={feedback.type === 'error' ? 'destructive' : 'success'}>
                        {feedback.message}
                    </Alert>
                </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-8">
                {/* Dados Pessoais */}
                <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-8 relative">
                    <div className="absolute left-0 top-8 w-1.5 h-12 bg-[#f9b410] rounded-r-full" />
                    <h3 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                        <User className="w-7 h-7 text-[#f9b410]" />
                        Dados Pessoais
                    </h3>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900">
                                Nome Completo <span className="text-red-500">*</span>
                            </label>
                            <Input
                                icon={User}
                                value={formData.full_name}
                                onChange={(e) => handleChange('full_name', e.target.value)}
                                placeholder="Ex: Maria Silva"
                                className="h-12"
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900">
                                Email <span className="text-red-500">*</span>
                            </label>
                            <Input
                                icon={Mail}
                                type="email"
                                value={formData.email}
                                onChange={(e) => handleChange('email', e.target.value)}
                                placeholder="nome@beehouse.com"
                                className="h-12"
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900">CPF</label>
                            <Input
                                icon={CreditCard}
                                value={formData.cpf}
                                onChange={(e) => handleChange('cpf', e.target.value)}
                                placeholder="000.000.000-00"
                                className="h-12"
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900">
                                Telefone
                            </label>
                            <Input
                                icon={Phone}
                                value={formData.phone}
                                onChange={(e) => handleChange('phone', e.target.value)}
                                placeholder="(11) 99999-9999"
                                className="h-12"
                            />
                        </div>
                    </div>
                </div>

                {/* Dados Contratuais */}
                <div className="bg-white rounded-2xl shadow-lg border border-gray-100 p-8 relative overflow-visible z-10">
                    <div className="absolute left-0 top-8 w-1.5 h-12 bg-zinc-800 rounded-r-full" />

                    <h3 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                        <Briefcase className="w-7 h-7 text-gray-700" />
                        Dados Contratuais
                    </h3>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900">
                                Departamento <span className="text-red-500">*</span>
                            </label>
                            <Select
                                value={formData.department}
                                onValueChange={(value) => handleChange('department', value)}
                            >
                                <SelectTrigger className="h-12">
                                    <Building2 className="w-4 h-4 mr-2 text-gray-400" />
                                    <SelectValue placeholder="Selecione um departamento..." />
                                </SelectTrigger>
                                <SelectContent>
                                    {departmentsList.map((dept) => (
                                        <SelectItem key={dept} value={dept}>
                                            {dept}
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>

                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900">
                                Cargo <span className="text-red-500">*</span>
                            </label>
                            <Input
                                icon={Briefcase}
                                value={formData.role}
                                onChange={(e) => handleChange('role', e.target.value)}
                                placeholder="Ex: Desenvolvedor"
                                className="h-12"
                            />
                        </div>
                    </div>
                </div>

                <div className="flex items-center justify-end gap-4 pt-6">
                    <Link href="/colaboradores">
                        <Button variant="ghost" size="lg">
                            Cancelar
                        </Button>
                    </Link>
                    <Button
                        type="submit"
                        size="lg"
                        loading={loading}
                        className="px-10 font-bold text-black shadow-lg shadow-[#f9b410]/30 hover:scale-[1.02] transition-transform"
                    >
                        <Check className="w-5 h-5 mr-2" />
                        Salvar Cadastro
                    </Button>
                </div>
            </form>
        </div>
    )
}

// pages/colaboradores/novo.vue
<template>
  <div class="max-w-5xl mx-auto py-6">
    <div class="flex items-center gap-4 mb-8">
      <UButton 
        icon="i-heroicons-arrow-left" 
        color="neutral" 
        variant="ghost" 
        to="/colaboradores"
        class="rounded-full hover:bg-gray-100"
      />
      <div>
        <h1 class="text-3xl font-bold text-gray-900">Novo Colaborador</h1>
        <p class="text-gray-500">Preencha os dados para cadastrar um novo funcionário.</p>
      </div>
    </div>

    <div class="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      <UForm :schema="schema" :state="state" class="p-8 space-y-6" @submit="onSubmit">
        
        <div>
          <h3 class="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <UIcon name="i-heroicons-user" class="text-primary-500" />
            Dados Pessoais
          </h3>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <UFormGroup label="Nome Completo" name="full_name" class="text-gray-700">
              <UInput v-model="state.full_name" placeholder="Ex: João da Silva" class="w-full" />
            </UFormGroup>

            <UFormGroup label="Email Corporativo" name="email" class="text-gray-700">
              <UInput v-model="state.email" type="email" placeholder="joao@beehouse.com" class="w-full" />
            </UFormGroup>

            <UFormGroup label="CPF" name="cpf" class="text-gray-700">
              <UInput v-model="state.cpf" placeholder="000.000.000-00" class="w-full" />
            </UFormGroup>

            <UFormGroup label="Telefone / WhatsApp" name="phone" class="text-gray-700">
              <UInput v-model="state.phone" placeholder="(00) 90000-0000" class="w-full" />
            </UFormGroup>
          </div>
        </div>

        <div class="border-t border-gray-100 my-6"></div>

        <div>
          <h3 class="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <UIcon name="i-heroicons-briefcase" class="text-primary-500" />
            Dados Contratuais
          </h3>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <UFormGroup label="Departamento" name="department" class="text-gray-700">
              <USelect 
                v-model="state.department" 
                :options="['Administrativo', 'Comercial', 'Financeiro', 'Marketing', 'Operacional', 'RH', 'TI']" 
                placeholder="Selecione..."
                class="w-full"
              />
            </UFormGroup>

            <UFormGroup label="Cargo / Função" name="role" class="text-gray-700">
              <UInput v-model="state.role" placeholder="Ex: Analista Pleno" class="w-full" />
            </UFormGroup>
          </div>
        </div>

        <div class="flex items-center justify-end gap-4 pt-6 border-t border-gray-100 mt-6">
          <UButton color="neutral" variant="ghost" to="/colaboradores">
            Cancelar
          </UButton>
          <UButton type="submit" color="primary" size="md" :loading="loading" icon="i-heroicons-check">
            Salvar Cadastro
          </UButton>
        </div>
      </UForm>
    </div>
  </div>
</template>

<script setup lang="ts">
import { z } from 'zod'
import type { FormSubmitEvent } from '#ui/types'

const client = useSupabaseClient() as any
const loading = ref(false)

const schema = z.object({
  full_name: z.string().min(3, 'Nome muito curto'),
  email: z.string().email('Email inválido'),
  department: z.string().min(1, 'Selecione um departamento'),
  role: z.string().min(1, 'Cargo é obrigatório'),
  cpf: z.string().optional(),
  phone: z.string().optional()
})

type Schema = z.output<typeof schema>

const state = reactive({
  full_name: '',
  email: '',
  cpf: '',
  phone: '',
  department: '',
  role: ''
})

async function onSubmit(event: FormSubmitEvent<Schema>) {
  loading.value = true
  try {
    const { error } = await client.from('collaborators').insert({
      full_name: event.data.full_name,
      email: event.data.email,
      status: 'ativo'
      // Outros campos serão adicionados conforme a tabela evoluir
    })

    if (error) throw error
    
    // Feedback visual simples ou redirecionamento
    alert('Colaborador cadastrado com sucesso!')
    navigateTo('/colaboradores')
  } catch (e: any) {
    console.error(e)
    alert('Erro ao salvar: ' + (e.message || e))
  } finally {
    loading.value = false
  }
}
</script>
